name: CPU tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

defaults:
  run:
    shell: bash

jobs:
  cpu-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: "macOS-11", python-version: "3.10", pytorch-version: "2.0"}
          - {os: "ubuntu-20.04", python-version: "3.10", pytorch-version: "2.0"}
          - {os: "windows-2022", python-version: "3.10", pytorch-version: "2.0"}
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pytest -r requirements.txt
        pip list

    - name: Run tests
      run: |
        pytest -v --durations=10
