name: CPU tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

defaults:
  run:
    shell: bash

jobs:
  cpu-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: "macOS-11", python-version: "3.10"}
          - {os: "ubuntu-20.04", python-version: "3.10"}
          - {os: "windows-2022", python-version: "3.10"}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          setup.py

    - name: Run tests without the package installed
      run: |
        pip install pytest -r requirements.txt
        pip list

        pytest --disable-pytest-warnings --strict-markers --color=yes

    - name: Run tests
      run: |
        pip install . --no-deps

        pytest -v --durations=10 --disable-pytest-warnings --strict-markers --color=yes
